//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContraDrift.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TelescopeProgId {
            get {
                return ((string)(this["TelescopeProgId"]));
            }
            set {
                this["TelescopeProgId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Status {
            get {
                return ((string)(this["Status"]));
            }
            set {
                this["Status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WatchFolder {
            get {
                return ((string)(this["WatchFolder"]));
            }
            set {
                this["WatchFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PID_Setting_Kp_RA {
            get {
                return ((double)(this["PID_Setting_Kp_RA"]));
            }
            set {
                this["PID_Setting_Kp_RA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PID_Setting_Ki_RA {
            get {
                return ((double)(this["PID_Setting_Ki_RA"]));
            }
            set {
                this["PID_Setting_Ki_RA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PID_Setting_Kd_RA {
            get {
                return ((double)(this["PID_Setting_Kd_RA"]));
            }
            set {
                this["PID_Setting_Kd_RA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PID_Setting_Kp_DEC {
            get {
                return ((double)(this["PID_Setting_Kp_DEC"]));
            }
            set {
                this["PID_Setting_Kp_DEC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PID_Setting_Ki_DEC {
            get {
                return ((double)(this["PID_Setting_Ki_DEC"]));
            }
            set {
                this["PID_Setting_Ki_DEC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PID_Setting_Kd_DEC {
            get {
                return ((double)(this["PID_Setting_Kd_DEC"]));
            }
            set {
                this["PID_Setting_Kd_DEC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double PID_Setting_Nfilt_RA {
            get {
                return ((double)(this["PID_Setting_Nfilt_RA"]));
            }
            set {
                this["PID_Setting_Nfilt_RA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double PID_Setting_Nfilt_DEC {
            get {
                return ((double)(this["PID_Setting_Nfilt_DEC"]));
            }
            set {
                this["PID_Setting_Nfilt_DEC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PID_Setting_Kp_RA_filter {
            get {
                return ((double)(this["PID_Setting_Kp_RA_filter"]));
            }
            set {
                this["PID_Setting_Kp_RA_filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PID_Setting_Ki_RA_filter {
            get {
                return ((double)(this["PID_Setting_Ki_RA_filter"]));
            }
            set {
                this["PID_Setting_Ki_RA_filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PID_Setting_Kd_RA_filter {
            get {
                return ((double)(this["PID_Setting_Kd_RA_filter"]));
            }
            set {
                this["PID_Setting_Kd_RA_filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PID_Setting_Kp_DEC_filter {
            get {
                return ((double)(this["PID_Setting_Kp_DEC_filter"]));
            }
            set {
                this["PID_Setting_Kp_DEC_filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PID_Setting_Ki_DEC_filter {
            get {
                return ((double)(this["PID_Setting_Ki_DEC_filter"]));
            }
            set {
                this["PID_Setting_Ki_DEC_filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double PID_Setting_Kd_DEC_filter {
            get {
                return ((double)(this["PID_Setting_Kd_DEC_filter"]));
            }
            set {
                this["PID_Setting_Kd_DEC_filter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProcessingTraditional {
            get {
                return ((bool)(this["ProcessingTraditional"]));
            }
            set {
                this["ProcessingTraditional"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UCAC4_path {
            get {
                return ((string)(this["UCAC4_path"]));
            }
            set {
                this["UCAC4_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float DecRateLimitSetting {
            get {
                return ((float)(this["DecRateLimitSetting"]));
            }
            set {
                this["DecRateLimitSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float RaRateLimitSetting {
            get {
                return ((float)(this["RaRateLimitSetting"]));
            }
            set {
                this["RaRateLimitSetting"] = value;
            }
        }
    }
}
